resources:
  repositories:
  - repository: datagrid-reactive-tests
    type: github
    name: OutSystems/outsystems-datagrid-tests
    endpoint: OutSystems  

trigger:
  branches:
    include:
    - dev
variables:
  SourcesDirectory: '$(Build.SourcesDirectory)'
  Project: 'outsystems-datagrid-reactive'
  BuildConfiguration: 'Release'
  Config: '--configuration=$(BuildConfiguration)'
  TagName: 'v$(Build.BuildNumber)'
  
stages: 
- stage: Build
  displayName: 'Build'
  jobs:
  - job: Build
    displayName: 'Build Job'
    timeoutInMinutes: 8
    pool:
      vmImage: 'windows-latest'
    steps:

    - checkout: self
    - checkout: datagrid-reactive-tests 
    #Install dependencies
    - task: Npm@1
      displayName: 'npm install'
      inputs:
        workingDir: './outsystems-datagrid-reactive/code'
        verbose: false

    #Compile typescript files
    - task: Npm@1
      displayName: 'npm run build'
      inputs:
        workingDir: './outsystems-datagrid-reactive/code'
        command: custom
        verbose: false
        customCommand: 'run build'

    #Publish compiled file    
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: './outsystems-datagrid-reactive/code/dist/GridFramework.js'
        ArtifactName: 'GridFramework.js'
        publishLocation: 'Container'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: './outsystems-datagrid-reactive/code/styles/Grid.css'
        ArtifactName: 'Grid.css'
        publishLocation: 'Container'