# File: azure-pipelines.yml

resources:
  repositories:
  - repository: datagrid-web-tests
    type: github
    name: OutSystems/datagrid-web-tests
    endpoint: OutSystems

trigger:
  branches:
    include:
    - dev
variables:
  SourcesDirectory: '$(Build.SourcesDirectory)'
  Project: 'outsystems-datagrid-reactive'
  BuildConfiguration: 'Release'
  Config: '--configuration=$(BuildConfiguration)'
  TagName: 'v$(Build.BuildNumber)'
  BranchName: $(Build.SourceBranchName)
  ModuleName: $[ replace(variables['BranchName'], '-', '') ]
  
stages: 
- stage: Build
  displayName: 'Build'
  jobs:
  - job: Build
    displayName: 'Build Job'
    timeoutInMinutes: 8
    pool:
      vmImage: 'windows-latest'
    steps:

    #Checkout repositories
    - checkout: self
    - checkout: datagrid-web-tests

    - task: CmdLine@2
      name: test2aa
      displayName: 'iejgepigj'
      inputs:
        workingDirectory: './datagrid-web-tests/'
        script: echo $ModuleName
      continueOnError: false

    - task: CmdLine@2
      name: test2a
      displayName: 'taggj'
      inputs:
        workingDirectory: './datagrid-web-tests/'
        script: echo $TagName
      continueOnError: false

    #Install dependencies
    - task: Npm@1
      displayName: 'npm install'
      inputs:
        workingDir: './outsystems-datagrid-reactive/code'
        verbose: false

    #Compile typescript files
    - task: Npm@1
      displayName: 'npm run build'
      inputs:
        workingDir: './outsystems-datagrid-reactive/code'
        command: custom
        verbose: false
        customCommand: 'run build'

    #Publish compiled file    
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: './outsystems-datagrid-reactive/code/dist/GridFramework.js'
        ArtifactName: 'GridFramework.js'
        publishLocation: 'Container'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: './outsystems-datagrid-reactive/code/styles/Grid.css'
        ArtifactName: 'Grid.css'
        publishLocation: 'Container'

- template: 'jobs/azure-pipelines-reactive.yml'
  parameters:
    module: $ModuleName