# File: jobs/azure-pipelines-reactive.yml
parameters:
- name: browser
  displayName: Browser
  type: string
  default: chrome
  values:
  - chrome
  - safari
  - edge
  - firefox
  - chrome, safari, edge, firefox
- name: environment
  displayName: Environment
  type: string
  default: dev
  values:
  - qa
  - dev
- name: feature
  displayName: Feature
  type: string
  default: all
  values:
  - all
  - pagination
  - sort
  - filter
- name: priority
  displayName: Priority
  type: string
  default: all
  values:
  - all
  - high
  - medium
  - low
- name: module
  displayName: Module
  type: string
  default: 'GridReactive_Automation'
- name: currentBranch
  type: string
- name: sourceBranch
  type: string
- name: instances
  displayName: Max driver instances
  type: number
  default: 2

stages: 
- stage: CheckBranch
  jobs:
    - job: CheckBranchJob
      displayName: 'Check Branch Exists'
      pool:
            vmImage: 'windows-latest'
      steps:    
      #Format branch name
      - bash: |
            declare BRANCH 
            BRANCH=$(system.pullRequest.sourceBranch)
            echo "GridReactive_Automation_${BRANCH//[-]/}"
            echo "##vso[task.setvariable variable=branch;]GridReactive_Automation_${BRANCH//[-]/}"
            echo "##vso[task.setvariable variable=module;isoutput=true]GridReactive_Automation_${BRANCH//[-]/}"
        name: branch_name

      #Ping sample test page
      #Sets skip variable as true if sample doesnt exist.
      - bash: |
          status=$(curl -s --head -w %{http_code} $(ENV_URL)/$(branch)/ -o /dev/null)
          echo $status
          echo $(ENV_URL)/$(branch)/
          if [[ $status = 404 ]]
          then
            echo "##vso[task.setvariable variable=skip;isoutput=true]true"
          fi
        displayName: "Ping sample test page"
        name: "skipTests"


- stage: Tests
  #Only run tests if not in dev branch
  condition: and(ne(stageDependencies.CheckBranch.outputs['CheckBranchJob.skipTests.skip'], 'true'), ne(variables['Build.SourceBranchName'], 'dev'))
  displayName: 'Tests'
  variables:
    - group: "Services Credentials"
  
  jobs:
  - job: Run_Tests
    displayName: 'Run tests'
    timeoutInMinutes: 180
    variables:
      module: $[ stageDependencies.CheckBranch.CheckBranchJob.outputs['branch_name.module'] ]
    pool:
          vmImage: 'windows-latest'
    steps:   
    - checkout: outsystems-datagrid-tests 
    - template: './azure/azure-pipelines-template.yml@outsystems-datagrid-tests'
      parameters:
        grid: reactive
        module: $(module)
        browser: ${{ parameters.browser }}
        environment: ${{ parameters.environment }}
        tags: ${{ parameters.feature }}
        priority: ${{ parameters.priority }}
        instances: ${{ parameters.instances }}
