// eslint-disable-next-line @typescript-eslint/no-unused-vars
namespace Providers.DataGrid.Wijmo.Helper {
	/**
	 * Reads the OutSystems column uniqueId previously stored on a Wijmo column instance.
	 * Returns undefined for columns that were not created through the wrapper (for example,
	 * autogenerated columns), in which case callers should fall back to the column binding.
	 *
	 * @param column Wijmo column to read the uniqueId from.
	 * @returns The OutSystems column uniqueId, or undefined when it was not set.
	 */
	export function GetColumnUniqueId(column: wijmo.grid.Column): string | undefined {
		return (column as unknown as Record<string, string>)?.[Constants.ColumnProperty.OSUniqueId];
	}

	/**
	 * Stores the OutSystems column uniqueId on a Wijmo column instance so features (e.g.
	 * ClickEvent, DirtyMark) can map a Wijmo column back to its OutSystems column.
	 *
	 * This intentionally replaces the previous use of Wijmo's `describedById` property:
	 * Wijmo renders `describedById` as an `aria-describedby` attribute pointing to an element
	 * that does not exist, producing "Broken ARIA reference" accessibility errors (flagged by
	 * WAVE). Storing the uniqueId on a private expando keeps the mapping without emitting
	 * invalid ARIA markup.
	 *
	 * @param column Wijmo column to tag.
	 * @param uniqueId OutSystems column uniqueId.
	 */
	export function SetColumnUniqueId(column: wijmo.grid.Column, uniqueId: string): void {
		(column as unknown as Record<string, string>)[Constants.ColumnProperty.OSUniqueId] = uniqueId;
	}
}
