<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="OutSystems.HubEdition.RuntimePlatform">
      <HintPath>..\DataGridUtils\Source\NET\Bin\OutSystems.HubEdition.RuntimePlatform.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="OutSystems.HubEdition.DatabaseAbstractionLayer">
      <HintPath>..\DataGridUtils\Source\NET\Bin\OutSystems.HubEdition.DatabaseAbstractionLayer.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="OutSystems.NssDataGridUtils">
      <HintPath>..\DataGridUtils\Source\NET\bin\OutSystems.NssDataGridUtils.dll</HintPath>
    </Reference>
    <Reference Include="OutSystems.RuntimeCommon">
      <HintPath>..\DataGridUtils\Source\NET\Bin\OutSystems.RuntimeCommon.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

</Project>
