/**
 * Defines the interface for buildable objects
 */
/* eslint-disable @typescript-eslint/no-unused-vars */
interface IBuilder {
    /**
     * Build object, instantiating dependencies, and maniulating DOM when necessary
     */
    build(): void;
}

/**
 * Defines the interface for disposable objects
 */
interface IDisposable {
    /**
     * Dispose object and free up its used resources
     */
    dispose(): void;
}

/**
 * Defines the interface for objects with multiple DOM identifiers
 */
interface ISearchById {
    /**
     * Validates if object matched with the given id
     */
    equalsToID(id: string): boolean;
}

interface IValidation {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    validateAction(action: InternalEvents.Actions, ctx: any): string;
}

interface IProviderConfig<T> {
    setState(value: T): void;
}

interface IConfiguration {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    getProviderConfig(): any;
}

interface IConfigurationGrid extends IConfiguration {
    uniqueId: string;
}

interface IConfigurationColumn extends IConfiguration {
    align: string;
    autoGenerated: boolean;
    binding: string;
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    dataType: any;
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    editor: any;
    format: string;
    /** Id reference for the internal GenericColumn widget */
    genericColumnId: string;
    header: string;
    required: boolean;
    uniqueId: string;
}

interface IConfigurationColumnEditor extends IConfiguration {
    format: string;
    required: boolean;
}

/**
 * Define signature for OS communications
 * This method should be defined wherever need a JSON.stringify
 * 
 * @example GridAPI.Selection.getAllSelectionsDataSource
 */
interface ISerializable {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    serialize(): any 
}
