name: Pre-Release of OutSystems Datagrid

on:
    workflow_dispatch:
        inputs:
            new-version:
                description: 'New version to be set. (1.0.1)'
                type: string
                required: true
            release-date:
                description: 'Release date. (YYYY-MM-DD)'
                type: string
                required: true
            new-dev-release:
                description: 'Set the new dev version. (1.0.1)'
                type: string
                required: false

jobs:
    create-release-candidate:
        uses: OutSystems/ui-components.github-reusable-workflows/.github/workflows/pre-release.yaml@ff22715af93207fcdc56fcd5c0688eb497913f7f #v0.1.0-alpha
        with:
            new-version: ${{ inputs.new-version }}
            release-date: ${{ inputs.release-date }}
            new-dev-release: ${{ inputs.new-dev-release }}
