name: Release of OutSystems Datagrid

on:
    workflow_dispatch:
        inputs:
            new-version:
                description: 'Version to be released.'
                type: string
                required: true
            update-prerelease-into-latest:
                description: 'Update pre-release into latest.'
                type: boolean
                default: true
            delete-rc-branch:
                description: 'Delete rc* branch at the end of process.'
                type: boolean
                default: true

jobs:
    set-release-latest:
        uses: OutSystems/ui-components.github-reusable-workflows/.github/workflows/release.yaml@ff22715af93207fcdc56fcd5c0688eb497913f7f #v0.1.0-alpha
        with:
            new-version: ${{ inputs.new-version }}
            update-prerelease-into-latest: ${{ inputs.update-prerelease-into-latest }}
            delete-rc-branch: ${{ inputs.delete-rc-branch }}
